name = "PCAtolu"
uuid = "130318a0-d9f3-4f8e-bc76-b23d420e9b47"
authors = ["Tom7946 godinlu"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
